# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-08 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_weekly_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_log',
            name='travel_time',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
