# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-09 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_daily_log_travel_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_log',
            name='name',
        ),
        migrations.AddField(
            model_name='daily_log',
            name='comments',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
