# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-10 21:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20181009_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_log',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='daily_log',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2018, 10, 10, 21, 14, 15, 515769, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='daily_log',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 10, 21, 14, 15, 515841, tzinfo=utc)),
        ),
    ]
