# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-13 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20181011_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_log',
            name='week',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='report.weekly_report'),
            preserve_default=False,
        ),
    ]
