# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-13 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_daily_log_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekly_report',
            name='comments',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weekly_report',
            name='total_hours',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='weekly_report',
            name='total_miscelaneous',
            field=models.FloatField(default='0'),
        ),
    ]
