# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-14 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_auto_20181013_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_log',
            name='end_time',
            field=models.TimeField(default='5:00pm'),
        ),
        migrations.AlterField(
            model_name='daily_log',
            name='extra_time',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='daily_log',
            name='lunch_time',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='daily_log',
            name='start_time',
            field=models.TimeField(default='8:00am'),
        ),
        migrations.AlterField(
            model_name='daily_log',
            name='travel_time',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='weekly_report',
            name='comments',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
