# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-14 19:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0013_auto_20181014_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_log',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2018, 10, 14, 19, 33, 52, 503159, tzinfo=utc)),
        ),
    ]
