# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-16 01:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0014_auto_20181014_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weekly_report',
            old_name='total_miscelaneous',
            new_name='miscelaneous',
        ),
        migrations.AlterField(
            model_name='daily_log',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2018, 10, 16, 1, 16, 51, 463811, tzinfo=utc)),
        ),
    ]
