# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-16 17:57
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0015_auto_20181015_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekly_report',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='daily_log',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2018, 10, 16, 17, 56, 56, 890695, tzinfo=utc)),
        ),
    ]
