# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 21:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0017_auto_20181016_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_log',
            name='comments',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='daily_log',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2018, 10, 18, 21, 16, 50, 10524, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='weekly_report',
            name='comments',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
